version: "3"
services:

  openrov:
    build: openrov/
    restart: on-failure
    network_mode: "host"
    command: 192.168.2.215
    volumes:
      - "cockpit:/opt/openrov/cockpit"
      - "video:/video"
    ports:
      - "80:80"
      - "443:443"
      - "1883:1883"
      - "3000:3000"
      - "8080:8080"
      - "8200:8200"
      - "8300:8300"
      - "9229:9229"
    logging:
      options:
        max-size: "1000k"
        max-file: "10"

volumes:
  cockpit:
  video:
