version: "3"
services:

  openrov:
    build: openrov/
    restart: on-failure
    command: 192.168.2.215
    volumes:
      - "cockpit:/opt/openrov/cockpit"
      - "video:/video"
      - "assets/adjustments.json:/opt/openrov/cockpit/src/lib/adjustments.json"
      - "~/.gitconfig:/root/.gitconfig"
    ports:
      - "80:80"
      - "443:443"
      - "1883:1883"
      - "3000:3000"
      - "8080:8080"
      - "8200:8200"
      - "8300:8300"
      - "9229:9229"
    networks:
      scini:
        ipv4_address: 192.168.2.2
    logging:
      options:
        max-size: "500k"
        max-file: "10"
    depends_on:
      - fwdcam-mock
      - downcam-mock
      - upcam-mock
      - clumpcam-mock

  fwdcam-mock:
    build: imgsrv-mock/
    restart: on-failure
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    ports:
      - "8081"
    networks:
      scini:
        ipv4_address: 192.168.2.215
    logging:
      options:
        max-size: "50k"
        max-file: "10"

  downcam-mock:
    build: imgsrv-mock/
    restart: on-failure
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    ports:
      - "8081"
    networks:
      scini:
        ipv4_address: 192.168.2.218
    logging:
      options:
        max-size: "50k"
        max-file: "10"

  upcam-mock:
    build: imgsrv-mock/
    restart: on-failure
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    ports:
      - "8081"
    networks:
      scini:
        ipv4_address: 192.168.2.213
    logging:
      options:
        max-size: "50k"
        max-file: "10"

  clumpcam-mock:
    build: imgsrv-mock/
    restart: on-failure
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    ports:
      - "8081"
    networks:
      scini:
        ipv4_address: 192.168.2.211
    logging:
      options:
        max-size: "50k"
        max-file: "10"

  mqtt-fwd:
    build: mqttclient-mock/
    restart: on-failure
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    expose:
      - "1883"
      - "3000"
      - "50000"
    networks:
      scini:
        ipv4_address: 192.168.2.231
    logging:
      options:
        max-size: "500k"
        max-file: "10"
    depends_on:
      - openrov

  serial-fwd:
    build: serial-tester/
    restart: on-failure
    environment:
      - PARTNER=192.168.2.231
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    networks:
      scini:
        ipv4_address: 192.168.2.232
    logging:
      options:
        max-size: "500k"
        max-file: "10"
    depends_on:
      - mqtt-fwd

  mqtt-clump:
    build: mqttclient-mock/
    restart: on-failure
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    expose:
      - "1883"
      - "3000"
      - "50000"
    networks:
      scini:
        ipv4_address: 192.168.2.233
    logging:
      options:
        max-size: "500k"
        max-file: "10"
    depends_on:
      - openrov

networks:
  scini:
    external: true

volumes:
  cockpit:
  video:
