version: "3"
services:

  openrov:
    build: openrov/
    restart: on-failure
    command: 192.168.2.215 dev
    cap_add:
      - SYS_NICE
    volumes:
      - "images-dev:/opt/openrov/images"
      - "logs-dev:/opt/openrov/logs"
      - "data-dev:/opt/openrov/data"
      - "./assets/www:/opt/openrov/www"
      - "./assets/adjustments.dev.json:/opt/openrov/cockpit/src/lib/adjustments.json"
      - "./assets/mqttConfig.json:/opt/openrov/config/mqttConfig.json"
      - "~/.gitconfig:/root/.gitconfig"
    ports:
      - "80:80"
      - "443:443"
      - "1883:1883"
      - "3000:3000"
      - "7011:7011"
      - "8080:8080"
      - "8200:8200"
      - "8201:8201"
      - "8202:8202"
      - "8203:8203"
      - "8204:8204"
      - "8300:8300"
      - "9229:9229"
    networks:
      scini:
        ipv4_address: 192.168.2.2
    logging:
      options:
        max-size: "500k"
        max-file: "10"
    depends_on:
      - fwdcam-mock
      - downcam-mock
      - upcam-mock
      - clumpcam-mock

  fwdcam-mock:
    build: imgsrv-mock/
    restart: on-failure
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    ports:
      - "8081"
    networks:
      scini:
        ipv4_address: 192.168.2.215
    logging:
      options:
        max-size: "50k"
        max-file: "10"

  downcam-mock:
    build: imgsrv-mock/
    restart: on-failure
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    ports:
      - "8081:8081"
    networks:
      scini:
        ipv4_address: 192.168.2.218
    logging:
      options:
        max-size: "50k"
        max-file: "10"

  upcam-mock:
    build: imgsrv-mock/
    restart: on-failure
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    ports:
      - "8081"
    networks:
      scini:
        ipv4_address: 192.168.2.213
    logging:
      options:
        max-size: "50k"
        max-file: "10"

  clumpcam-mock:
    build: imgsrv-mock/
    restart: on-failure
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    ports:
      - "8081"
    networks:
      scini:
        ipv4_address: 192.168.2.211
    logging:
      options:
        max-size: "50k"
        max-file: "10"

  mqtt-fwd:
    build: mqttclient-mock/
    restart: on-failure
    environment:
      - MQTT_INTERFACE=eth0
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    expose:
      - "1883"
      - "3000"
      - "50000"
    networks:
      scini:
        ipv4_address: 192.168.2.231
    logging:
      options:
        max-size: "500k"
        max-file: "10"
    depends_on:
      - openrov

  serial-fwd:
    build: serial-tester/
    restart: on-failure
    environment:
      - PARTNER=192.168.2.231
      - NODEIDS="14 15 21 42 51 52"
    volumes:
      - "~/.gitconfig:/root/.gitconfig"
    ports:
      - "9222:9229"
    networks:
      scini:
        ipv4_address: 192.168.2.232
    logging:
      options:
        max-size: "500k"
        max-file: "10"
    depends_on:
      - mqtt-fwd

  file-browser:
    restart: always
    environment:
      - PORT=8000
      - CLOUDCMD_ROOT=/opt/openrov/
    ports:
      - "8000:8000"
    volumes:
      - "images-dev:/opt/openrov/images:ro"
      - "logs-dev:/opt/openrov/logs:ro"
      - "data-dev:/opt/openrov/data:ro"
      - "./assets:/opt/openrov/assets:rw"
    image: coderaiser/cloudcmd
    networks:
      scini:
        ipv4_address: 192.168.2.151
    logging:
      options:
        max-size: "500k"
        max-file: "10"

networks:
  scini:
    external: true

volumes:
  images-dev:
  logs-dev:
  data-dev:
