version: "3"
services:

  openrov:
    build: openrov/
    restart: always
    network_mode: "host"
    command: 192.168.2.215
    cap_add:
      - SYS_NICE
    volumes:
      - "images:/opt/openrov/images"
      - "logs:/opt/openrov/logs"
      - "data:/opt/openrov/data"
      - "./assets/www:/opt/openrov/www"
      - "./assets/mqttConfig.json:/opt/openrov/config/mqttConfig.json"
      - "./assets/adjustments.prod.json:/opt/openrov/cockpit/src/lib/adjustments.json"
    ports:
      - "80:80"
      - "443:443"
      - "1883:1883"
      - "3000:3000"
      - "7011:7011"
      - "8080:8080"
      - "8100:8200"
      - "8101:8201"
      - "8102:8202"
      - "8103:8203"
      - "8104:8204"
      - "8200:8200"
      - "8201:8201"
      - "8202:8202"
      - "8203:8203"
      - "8204:8204"
      - "8300:8300"
      - "9000:9000"
      - "9229:9229"
    logging:
      options:
        max-size: "1000k"
        max-file: "10"

  file-browser:
    restart: always
    environment:
      - PORT=8000
      - CLOUDCMD_ROOT=/opt/openrov/
    ports:
      - "8000:8000"
    volumes:
      - "images:/opt/openrov/images:ro"
      - "logs:/opt/openrov/logs:ro"
      - "data:/opt/openrov/data:ro"
      - "./assets:/opt/openrov/assets:rw"
    image: coderaiser/cloudcmd
    logging:
      options:
        max-size: "500k"
        max-file: "10"

volumes:
  images:
  logs:
  data:
