version: "3"
services:

  openrov:
    build: openrov/
    restart: always
    network_mode: "host"
    command: 192.168.2.215
    cap_add:
      - SYS_NICE
    volumes:
      - "cockpit:/opt/openrov/cockpit"
      - "images:/opt/openrov/images"
      - "logs:/opt/openrov/logs"
      - "www:/opt/openrov/www"
      - "data:/opt/openrov/data"
      - "~/.gitconfig:/root/.gitconfig"
    ports:
      - "80:80"
      - "443:443"
      - "1883:1883"
      - "3000:3000"
      - "7011:7011"
      - "8080:8080"
      - "8200:8200"
      - "8201:8201"
      - "8202:8202"
      - "8203:8203"
      - "8204:8204"
      - "8300:8300"
      - "9229:9229"
    logging:
      options:
        max-size: "1000k"
        max-file: "10"

volumes:
  cockpit:
  images:
  logs:
  www:
  data:
